pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

Singleton {
    id: root

    readonly property var roles: [
        { key: "terminal", title: "Terminal", icon: "terminal", category: "TerminalEmulator", shortcut: "Super+T" },
        { key: "browser", title: "Browser", icon: "language", category: "WebBrowser", shortcut: "" },
        { key: "files", title: "Files", icon: "folder", category: "FileManager", shortcut: "Super+E" },
        { key: "editor", title: "Code editor", icon: "code", category: "TextEditor", shortcut: "Super+C" }
    ]

    readonly property var all: DesktopEntries.applications.values

    function entry(role) {
        const id = Settings.apps[role] ?? "";
        return all.find(e => e.id === id) ?? null;
    }

    function candidates(role) {
        const r = roles.find(r => r.key === role);
        return all.filter(e => !e.noDisplay && e.categories.includes(r.category))
            .sort((a, b) => a.name.localeCompare(b.name));
    }

    function quote(arg) {
        return /[\s"'$]/.test(arg) ? "'" + arg.replace(/'/g, "'\\''") + "'" : arg;
    }

    function shellCommand(e) {
        const command = e.command.map(quote).join(" ");
        if (!e.runInTerminal) return command;
        const terminal = entry("terminal");
        const host = terminal && !terminal.runInTerminal ? quote(terminal.command[0]) : "ghostty";
        return host + " -e " + command;
    }

    function writeHyprland() {
        const lines = roles.map(r => {
            const e = entry(r.key);
            return e ? `    ${r.key} = ${JSON.stringify(shellCommand(e))},` : "";
        }).filter(l => l);
        const text = "-- Generated by the shell (Settings > Apps), do not edit\nreturn {\n" + lines.join("\n") + "\n}\n";
        writer.command = ["sh", "-c", "printf '%s' \"$1\" > \"$2\" && hyprctl reload", "sh", text, Quickshell.env("HOME") + "/.config/hypr/apps.lua"];
        writer.running = true;
    }

    function choose(role, e) {
        Settings.apps[role] = e.id;
        writeHyprland();
        if (role === "browser") Quickshell.execDetached(["xdg-settings", "set", "default-web-browser", e.id + ".desktop"]);
        if (role === "files") Quickshell.execDetached(["xdg-mime", "default", e.id + ".desktop", "inode/directory"]);
    }

    Connections {
        target: Settings
        function onGroupReset(group) {
            if (group === "apps") root.writeHyprland();
        }
    }

    Process {
        id: writer
    }
}
