// Design tokens: every size, spacing, radius, font and animation lives here.
// Values come from the Figma design. Colors live in Colors.qml (generated by matugen).
// Usage: import qs.theme  →  height: Theme.bar.height
//
// Each group is an inline component (e.g. `component Bar`), so the editor knows which
// properties exist. A plain QtObject would work too, but then VS Code can't autocomplete it.

pragma Singleton

import QtQuick
import Quickshell

Singleton {
    // Bar (Figma: "Left part", "middle", "Right part")
    component Bar: QtObject {
        readonly property int height: 55        // island height
        readonly property int padding: 16       // left/right padding inside an island
        readonly property int gap: 14           // space between items in an island
        readonly property int radius: 16        // outer island corner
        readonly property int centerMinWidth: 336   // center island never gets narrower
        readonly property int windowHeight: 320     // room for islands that grow downward
        readonly property real opacity: 0.85    // islands are translucent, blur comes from Hyprland
    }
    readonly property Bar bar: Bar {}

    // Buttons
    component Button: QtObject {
        readonly property int size: 40          // round buttons (gear, power, tray, workspaces)
        readonly property int iconSize: 20
    }
    readonly property Button button: Button {}

    // Workspaces
    component Workspaces: QtObject {
        readonly property int shown: 5          // always 5 visible, groups of 5
        readonly property int activeWidth: 88   // active workspace = wide pill
    }
    readonly property Workspaces workspaces: Workspaces {}

    // Battery ring around the power button
    component BatteryRing: QtObject {
        readonly property int size: 50
        readonly property int thickness: 3
        readonly property real trackOpacity: 0.28
        readonly property real lowLevel: 0.2    // below this: error color
    }
    readonly property BatteryRing batteryRing: BatteryRing {}

    // Corner radii
    component Radius: QtObject {
        readonly property int small: 8
        readonly property int medium: 16
        readonly property int large: 24
        readonly property int full: 999         // pill / circle
    }
    readonly property Radius radius: Radius {}

    // Spacing scale
    component Spacing: QtObject {
        readonly property int xs: 4
        readonly property int sm: 8
        readonly property int md: 12
        readonly property int lg: 16
        readonly property int xl: 24
    }
    readonly property Spacing spacing: Spacing {}

    // Fonts (Inter: `sudo dnf install rsms-inter-fonts`; Material Symbols Rounded and
    // Symbols Nerd Font from their GitHub releases)
    component Font: QtObject {
        readonly property string family: "Inter"
        readonly property string icons: "Material Symbols Rounded"
        readonly property string logos: "Symbols Nerd Font"   // OS logos
        readonly property int small: 12
        readonly property int normal: 14
        readonly property int large: 16
        readonly property int clock: 20
    }
    readonly property Font font: Font {}

    // Motion: Material 3 durations (ms) and easing curves.
    // Usage: Behavior on width { NumberAnimation { duration: Theme.anim.medium;
    //            easing.type: Easing.BezierSpline; easing.bezierCurve: Theme.anim.standard } }
    component Anim: QtObject {
        readonly property int fast: 150
        readonly property int medium: 300
        readonly property int slow: 500
        readonly property int island: 550       // dynamic island grow/shrink
        readonly property real overshoot: 1.2   // how far it springs past its size (Apple-like)

        readonly property list<real> standard:        [0.2, 0, 0, 1, 1, 1]
        readonly property list<real> emphasizedDecel: [0.05, 0.7, 0.1, 1, 1, 1] // things appearing
        readonly property list<real> emphasizedAccel: [0.3, 0, 0.8, 0.15, 1, 1] // things disappearing
    }
    readonly property Anim anim: Anim {}
}
